### ISSUE TITLE
If enabled in Chrome I can't view some PDF files

### ISSUE THREAD

**Issue by doublej42** [stormpath/jwt-inspector#7]
I just get a blank screen when I view a PDF if this is enabled.

**Comment by rorheden** [comment]
Thank you for reporting this issue!

I just tried accessing http://www.orimi.com/pdf-test.pdf and that rendered fine for me with the extension enabled. Does that also render blank for you? If not, then could you provide a URL to a PDF that reproduces the issue? Also, do you have any other extensions enabled? And could you go to http://www.whatsmybrowser.org/ and share your URL, so I can see exactly what OS/browser version that you're using?

Thanks!

**Comment by doublej42** [comment]
http://www.nanaimo.ca/assets/Departments/Building~Inspection/Publications~and~Forms/Building%20Stats%202015.pdf this was the most recent PDF I had issues with. I disabled all my extensions one by one until it worked.

The Test Link loaded once for me blank but a ctrl+F5 let it load. It's been hard to repeat on most PDF's till I found the above link and it was 100% of the time failed.

http://whatsmybrowser.org/b/FTG6A9J

I'm going to disable all my addons and isolate it after I post this.

**Comment by doublej42** [comment]
Thank you for your time. I'm going to be closing this issue as I found that Chrome PDF gets flaky with multiple addons enabled. No single  Addon caused the issue but it looks like combinations of addons caused trouble. JWT Just seemed to be the one that in my list kicked me over the limit.

http://imgur.com/a/yuEbH

**Comment by rorheden** [comment]
Thanks for letting me know about this! I actually created a new issue for this to minimize the likelyhood of this happening. See #8.
